### PR TITLE
make importable

### PR DESCRIPTION
**Pull request by pwqw**
Solve [issue#10](https://github.com/everythingwillbetakenaway/DX7-Supercollider/issues/10)

### CODE REVIEW

**Comment by everythingwillbetakenaway** [comment]
Sorry, I didn't understand what is this for? I really want to keep the process very simple (For newbie users). You seem to remove global mainCaller function why is that? Example.scd is a good idea though.

**Comment by pwqw** [comment]
I share with you the idea of keeping it simple.. But the reason to make it importable is because when I use a global [ProxySpace](http://doc.sccode.org/Classes/ProxySpace.html#examples) could originate problem with ~mainCaller as NodeProxy. Is what I say correct?

In addition, it is easier to embed in any code in a more dynamic way and I can call as I want the variable _(~mainCaller)_ that executes the sound, without having to modificate the original code _DX7.scd_

...and the [final result](https://github.com/everythingwillbetakenaway/DX7-Supercollider/pull/11/files#diff-6111e0d4d2015d4c896395a2db695aa3R10) is not complex..

**Comment by everythingwillbetakenaway** [comment]
I re-checked the code. It seems fine! Thank you for your work.

**Comment by pwqw** [comment]
No Please. Thanks to you.

**Pull request merged**
